package main

import (
	"fmt"
	"strings"
)

// renderSpec builds the OpenAPI 3.1 YAML document for the discovered resources.
// Output is deterministic for a given set of resources.
func (g *OpenAPIGenerator) renderSpec(resources []apiResource) string {
	var sb strings.Builder
	base := strings.TrimRight(g.config.OpenAPI.BasePath, "/")

	// Header
	sb.WriteString("openapi: 3.1.0\n")
	sb.WriteString("info:\n")
	fmt.Fprintf(&sb, "  title: %s\n", g.config.OpenAPI.Title)
	fmt.Fprintf(&sb, "  version: \"%s\"\n", g.config.OpenAPI.Version)
	sb.WriteString("  description: Auto-generated by convex-gen from *Api.ts modules. Do not edit by hand.\n")
	if g.config.OpenAPI.ServerURL != "" {
		sb.WriteString("servers:\n")
		fmt.Fprintf(&sb, "  - url: %s\n", g.config.OpenAPI.ServerURL)
	}
	sb.WriteString("security:\n")
	sb.WriteString("  - bearerAuth: []\n")

	// Paths
	sb.WriteString("paths:\n")
	for _, r := range resources {
		g.renderPaths(&sb, base, r)
	}

	// Components
	sb.WriteString("components:\n")
	sb.WriteString("  securitySchemes:\n")
	sb.WriteString("    bearerAuth:\n")
	sb.WriteString("      type: http\n")
	sb.WriteString("      scheme: bearer\n")
	sb.WriteString("  schemas:\n")
	for _, r := range resources {
		g.renderSchemas(&sb, r)
	}
	g.renderErrorSchema(&sb)
	g.renderResponses(&sb)

	return sb.String()
}

func (g *OpenAPIGenerator) renderPaths(sb *strings.Builder, base string, r apiResource) {
	tag := r.pathSegment
	s := r.schemaBase

	// Collection: POST (create)
	fmt.Fprintf(sb, "  %s/%s:\n", base, r.pathSegment)
	sb.WriteString("    post:\n")
	fmt.Fprintf(sb, "      operationId: create%s\n", s)
	fmt.Fprintf(sb, "      tags: [%s]\n", tag)
	sb.WriteString("      requestBody:\n")
	sb.WriteString("        required: true\n")
	sb.WriteString("        content:\n")
	sb.WriteString("          application/json:\n")
	fmt.Fprintf(sb, "            schema: { $ref: \"#/components/schemas/%sInput\" }\n", s)
	sb.WriteString("      responses:\n")
	fmt.Fprintf(sb, "        \"201\": { description: Created, content: { application/json: { schema: { $ref: \"#/components/schemas/%s\" } } } }\n", s)
	sb.WriteString("        \"400\": { $ref: \"#/components/responses/BadRequest\" }\n")
	sb.WriteString("        \"401\": { $ref: \"#/components/responses/Unauthorized\" }\n")
	sb.WriteString("        \"403\": { $ref: \"#/components/responses/Forbidden\" }\n")
	sb.WriteString("        \"422\": { $ref: \"#/components/responses/ValidationError\" }\n")

	// Item: GET / PATCH / DELETE
	fmt.Fprintf(sb, "  %s/%s/{id}:\n", base, r.pathSegment)
	sb.WriteString("    parameters:\n")
	sb.WriteString("      - name: id\n        in: path\n        required: true\n        schema: { type: string }\n")

	sb.WriteString("    get:\n")
	fmt.Fprintf(sb, "      operationId: get%s\n", s)
	fmt.Fprintf(sb, "      tags: [%s]\n", tag)
	sb.WriteString("      responses:\n")
	fmt.Fprintf(sb, "        \"200\": { description: OK, content: { application/json: { schema: { $ref: \"#/components/schemas/%s\" } } } }\n", s)
	sb.WriteString("        \"401\": { $ref: \"#/components/responses/Unauthorized\" }\n")
	sb.WriteString("        \"403\": { $ref: \"#/components/responses/Forbidden\" }\n")
	sb.WriteString("        \"404\": { $ref: \"#/components/responses/NotFound\" }\n")

	sb.WriteString("    patch:\n")
	fmt.Fprintf(sb, "      operationId: update%s\n", s)
	fmt.Fprintf(sb, "      tags: [%s]\n", tag)
	sb.WriteString("      requestBody:\n")
	sb.WriteString("        required: true\n")
	sb.WriteString("        content:\n")
	sb.WriteString("          application/json:\n")
	fmt.Fprintf(sb, "            schema: { $ref: \"#/components/schemas/%sPatch\" }\n", s)
	sb.WriteString("      responses:\n")
	fmt.Fprintf(sb, "        \"200\": { description: OK, content: { application/json: { schema: { $ref: \"#/components/schemas/%s\" } } } }\n", s)
	sb.WriteString("        \"400\": { $ref: \"#/components/responses/BadRequest\" }\n")
	sb.WriteString("        \"401\": { $ref: \"#/components/responses/Unauthorized\" }\n")
	sb.WriteString("        \"403\": { $ref: \"#/components/responses/Forbidden\" }\n")
	sb.WriteString("        \"404\": { $ref: \"#/components/responses/NotFound\" }\n")

	sb.WriteString("    delete:\n")
	fmt.Fprintf(sb, "      operationId: delete%s\n", s)
	fmt.Fprintf(sb, "      tags: [%s]\n", tag)
	sb.WriteString("      responses:\n")
	sb.WriteString("        \"204\": { description: Deleted }\n")
	sb.WriteString("        \"401\": { $ref: \"#/components/responses/Unauthorized\" }\n")
	sb.WriteString("        \"403\": { $ref: \"#/components/responses/Forbidden\" }\n")
	sb.WriteString("        \"404\": { $ref: \"#/components/responses/NotFound\" }\n")
}

func (g *OpenAPIGenerator) renderSchemas(sb *strings.Builder, r apiResource) {
	// Output schema: fields not present in input or patch are read-only.
	writable := map[string]bool{}
	for _, f := range r.input {
		writable[f.Name] = true
	}
	for _, f := range r.patch {
		writable[f.Name] = true
	}
	readOnly := map[string]bool{}
	for _, f := range r.output {
		if !writable[f.Name] {
			readOnly[f.Name] = true
		}
	}

	writeSchema(sb, r.schemaBase, r.output, readOnly)
	writeSchema(sb, r.schemaBase+"Input", r.input, nil)
	if len(r.patch) > 0 {
		writeSchema(sb, r.schemaBase+"Patch", r.patch, nil)
	}
}

func writeSchema(sb *strings.Builder, name string, fields []FieldInfo, readOnly map[string]bool) {
	fmt.Fprintf(sb, "    %s:\n", name)
	sb.WriteString("      type: object\n")
	var required []string
	for _, f := range fields {
		if !f.Optional {
			required = append(required, f.Name)
		}
	}
	if len(required) > 0 {
		sb.WriteString("      required:\n")
		for _, r := range required {
			fmt.Fprintf(sb, "        - %s\n", r)
		}
	}
	sb.WriteString("      additionalProperties: false\n")
	sb.WriteString("      properties:\n")
	for _, f := range fields {
		writeProperty(sb, f, readOnly[f.Name])
	}
}

func writeProperty(sb *strings.Builder, f FieldInfo, ro bool) {
	fmt.Fprintf(sb, "        %s:\n", f.Name)
	switch f.Type {
	case "array":
		sb.WriteString("          type: array\n")
		fmt.Fprintf(sb, "          items: { type: %s }\n", openapiScalar(f.ArrayType))
	case "union":
		sb.WriteString("          type: string\n")
		if len(f.Literals) > 0 {
			quoted := make([]string, len(f.Literals))
			for i, l := range f.Literals {
				quoted[i] = fmt.Sprintf("%q", l)
			}
			fmt.Fprintf(sb, "          enum: [%s]\n", strings.Join(quoted, ", "))
		}
	default:
		fmt.Fprintf(sb, "          type: %s\n", openapiScalar(f.Type))
	}
	if ro {
		sb.WriteString("          readOnly: true\n")
	}
}

func openapiScalar(t string) string {
	switch t {
	case "string", "id", "":
		return "string"
	case "number":
		return "number"
	case "boolean":
		return "boolean"
	default:
		return "object"
	}
}

func (g *OpenAPIGenerator) renderErrorSchema(sb *strings.Builder) {
	sb.WriteString("    Error:\n")
	sb.WriteString("      type: object\n")
	sb.WriteString("      required: [error]\n")
	sb.WriteString("      properties:\n")
	sb.WriteString("        error:\n")
	sb.WriteString("          type: object\n")
	sb.WriteString("          required: [code, message]\n")
	sb.WriteString("          properties:\n")
	sb.WriteString("            code: { type: string }\n")
	sb.WriteString("            message: { type: string }\n")
}

func (g *OpenAPIGenerator) renderResponses(sb *strings.Builder) {
	sb.WriteString("  responses:\n")
	for _, r := range []struct{ name, desc string }{
		{"BadRequest", "Malformed request"},
		{"Unauthorized", "Missing or invalid API token"},
		{"Forbidden", "Token lacks the required scope"},
		{"NotFound", "Resource not found or not owned by the caller"},
		{"ValidationError", "Body failed validation"},
	} {
		fmt.Fprintf(sb, "    %s:\n", r.name)
		fmt.Fprintf(sb, "      description: %s\n", r.desc)
		sb.WriteString("      content: { application/json: { schema: { $ref: \"#/components/schemas/Error\" } } }\n")
	}
}
