package main

import (
	"path/filepath"
	"testing"
)

// writeFile is defined in maestro_validation_test.go and reused here.

func TestGoNeedsTest(t *testing.T) {
	root := t.TempDir()
	cfg := GoMissingTestsCheckConfig{AppPaths: []string{"pkg"}, ExcludePaths: []string{"/cmd/"}}

	src := filepath.Join(root, "pkg", "foo.go")
	writeFile(t, src, "package pkg\n")
	if !goNeedsTest(cfg, root, src) {
		t.Error("plain source in scope should need a test")
	}

	testF := filepath.Join(root, "pkg", "foo_test.go")
	writeFile(t, testF, "package pkg\n")
	if goNeedsTest(cfg, root, testF) {
		t.Error("_test.go must never need a test")
	}

	docF := filepath.Join(root, "pkg", "doc.go")
	writeFile(t, docF, "package pkg\n")
	if goNeedsTest(cfg, root, docF) {
		t.Error("doc.go is skipped")
	}

	gen := filepath.Join(root, "pkg", "gen.go")
	writeFile(t, gen, "// Code generated by thing. DO NOT EDIT.\npackage pkg\n")
	if goNeedsTest(cfg, root, gen) {
		t.Error("generated file is skipped")
	}

	excluded := filepath.Join(root, "cmd", "tool", "main.go")
	writeFile(t, excluded, "package main\n")
	if goNeedsTest(cfg, root, excluded) {
		t.Error("/cmd/ excluded path is skipped")
	}

	outOfScope := filepath.Join(root, "other", "bar.go")
	writeFile(t, outOfScope, "package other\n")
	if goNeedsTest(cfg, root, outOfScope) {
		t.Error("out-of-appPaths file is skipped")
	}
}

func TestCollectGoMissingStaged(t *testing.T) {
	root := t.TempDir()
	cfg := GoMissingTestsCheckConfig{AppPaths: []string{"pkg"}}

	// Package A: source only, no test → missing.
	a := filepath.Join(root, "pkg", "a", "a.go")
	writeFile(t, a, "package a\n")
	// Package B: source + test → ok.
	b := filepath.Join(root, "pkg", "b", "b.go")
	writeFile(t, b, "package b\n")
	writeFile(t, filepath.Join(root, "pkg", "b", "b_test.go"), "package b\n")

	missing, err := collectGoMissingPackages(cfg, root, []string{a, b}, "staged")
	if err != nil {
		t.Fatal(err)
	}
	if len(missing) != 1 || filepath.Base(missing[0]) != "a" {
		t.Fatalf("missing = %v, want [pkg/a]", missing)
	}
}

func TestCollectGoMissingAll(t *testing.T) {
	root := t.TempDir()
	cfg := GoMissingTestsCheckConfig{AppPaths: []string{"pkg"}}
	writeFile(t, filepath.Join(root, "pkg", "a", "a.go"), "package a\n") // missing
	writeFile(t, filepath.Join(root, "pkg", "b", "b.go"), "package b\n") // ok
	writeFile(t, filepath.Join(root, "pkg", "b", "b_test.go"), "package b\n")
	writeFile(t, filepath.Join(root, "pkg", "vendor", "v.go"), "package v\n") // vendor skipped

	missing, err := collectGoMissingPackages(cfg, root, nil, "all")
	if err != nil {
		t.Fatal(err)
	}
	if len(missing) != 1 || filepath.Base(missing[0]) != "a" {
		t.Fatalf("missing = %v, want [pkg/a]", missing)
	}
}

func TestCollectGoMissingUnknownMode(t *testing.T) {
	_, err := collectGoMissingPackages(GoMissingTestsCheckConfig{}, t.TempDir(), nil, "bogus")
	if err == nil {
		t.Fatal("unknown mode should error")
	}
}
